# The PostgreSQL database connection string.
postgres_uri = "postgres://username:password@localhost/quoteyou"

# For running directly from the source directory, set this to "public" or omit it.
public_dir = "/usr/share/thequotebook"

# The address on which the server should listen.
bind_address = "0.0.0.0:3000"

# The public URL of the server, to be used for generating links to it.
base_url = "http://localhost:3000/"

# The client ID used for Google login.
google_client_id = "abc123"
